### ISSUE TITLE
Need jump lists (anchors) for headings

### ISSUE THREAD

**Issue by annajiat** [LibraryCarpentry/lc-spreadsheets#126] opened 2022-01-19 23:34 UTC
@zkamvar
We need to update style for this lesson so that jump lists (anchors for different sections) becomes automatically available for different levels of headings.

**Comment by morskyjezek** [comment] 2022-06-13 16:13
Hi @annajiat - is this an issue only for this lesson, or does this issue affect all Carpentries lessons?

**Comment by morskyjezek** [comment] 2022-06-14 15:11
Hi @annajiat - thanks for this suggestion. I agree that the individual subheads should generate anchors to facilitate navigation and reference throughout the lessons. It appears to me that this issue is one that affects all of the Library Carpentry lessons and is a design issue that should be addressed across all lessons. It has been addressed in some of the other lessons, such as https://carpentries.github.io/maintainer-onboarding/05-communicate-advisors/index.html. Given that issue, this is something that should be communicated to the Library Carpentry Curriculum Advisory Committee, and Core Team.

**Closed** 2022-06-16 23:30 UTC

**Comment by zkamvar** [comment] 2022-06-20 18:56
@morskyjezek, for context, @annajiat had asked about updating the styling for the lessons across The Carpentries organisations to include these links and I asked him to tag me in the lessons that needed it. Because it has to do with styling and not content, it is not an issue for the LC CAC.

That being said, you are correct that we are planning to update the lessons at the beginning of 2023. Shortly before the transition, all lessons will be updated with the latest styles. Once lessons are transitioned, requests for updates like this will no longer be an issue as updates to the style will be deployed across the entire infrastructure automatically.

**Comment by morskyjezek** [comment] 2022-06-20 18:59
Thanks @zkamvar for this context. I agree this is an important design feature. Should we reopen the issue, or is it sufficient that the issue is here and you're tagged?

**Comment by zkamvar** [comment] 2022-06-20 19:02
No, this issue does not need to be reopened. It is sufficient that it is here and I am tagged.

My main motivation for these issues was so that I could succinctly demonstrate the need for the new lesson infrastructure: https://carpentries.org/blog/2022/01/live-lesson-infrastructure/#for-maintainers-getting-the-latest-features

**Comment by morskyjezek** [comment] 2022-06-20 19:42
Great. And thanks for sharing the post!

**Comment by chennesy** [comment] 2022-06-20 21:44
Thanks @morskyjezek and @zkamvar for clarifying that because this is a style issue it falls outside of LC-CAC's scope. I'll share a quick update with LC-CAC in July so that we're all aware of the distinction, and note the plans for LC lesson styles to be addressed in early 2023 (cool).
